/** \file fura_during_stim.c
    \brief Use output of fura_concentration to get mean, min and max [Fura]
           during a specific stimulation.
 */
#include "abaa.h"
int main(int argc, char *argv[])
{
  static char usage[] = \
    "usage: %s [-s --stim=integer] -f --start_fit=integer \n\n"
    "  -s --stim <positive integer>: the stimulation to fit (default 1)\n"
    "  -f --start_fit <positive integer>: sample point where decay fit starts\n\n"
    " The program reads [Fura] from the 'stdin', data are assumed organized in 3 columns:\n"
    "   Index Time and [Fura]\n"
    " Several data sets called 'loading curve', 'Stimulation 1', 'Stimulation 2', etc\n"
    " are assumed to be present with 2 blank lines (gnuplot style) separating each data\n"
    " set. Each set starts with its name following a '#', the next line also starts with a\n"
    " '#' and contains '# xxx observations', where 'xxx' is the number of observations in\n"
    " the data set. The program goes to stimulation specified by 's' (default 1) and starts\n"
    " dealing with data starting from observation specified by parameter 'f'. The value of\n"
    " the latter parameter should be set to the value given in line '# fit started from point yy'\n"
    " in the file generated by a call to 'fit_ratiometric' ('yy' stands for the value of 'f').\n"
    " The program prints to the 'stdout' the mean, min and max [Fura] from point 'f'.\n\n";

  size_t stim=1;
  size_t start_fit;
  {int opt;
    static struct option long_options[] = {
      {"stim",optional_argument,NULL,'s'},
      {"start_fit",required_argument,NULL,'f'},
      {"help",no_argument,NULL,'h'},
      {NULL,0,NULL,0}
    };
    int long_index =0;
    while ((opt = getopt_long(argc,argv,
                              "hs:f:",
                              long_options,       
                              &long_index)) != -1) {
      switch(opt) {
      case 's':
      {
        stim = (size_t) atoi(optarg);
      }
      break;
      case 'f':
      {
        start_fit = (size_t) atof(optarg);
      }
      break;
      case 'h': printf(usage,argv[0]);
        return -1;
      default : fprintf(stderr,usage,argv[0]);
        return -1;
      }
    }
  }

  char buffer[256];
  int n1,n2;
  int in=0;
  // Read line per line
  while (fgets(buffer, sizeof(buffer), stdin) && in == 0)
    // Look for right pattern in line
    if (2 == sscanf(buffer, "# Stim %d with %d elements", &n1,&n2))
      // Extract relevant value
      if ((size_t) n1 == stim)
	in = 1;
  if (in==0)
    printf("Stim %d not found!\n", (int) stim);
  size_t n_obs = n2;
  // Advance start_fit-1 lines
  size_t i;
  for (i=0; i<start_fit; i++)
    fgets(buffer, sizeof(buffer), stdin);
  double fura_cum=0.0,fura_min=1e6,fura_max=0.0;
  for (; i<n_obs; i++) {
    float time,fura_val;
    double fura;
    fscanf(stdin,"%f %f",&time,&fura_val);
    fura = (double) fura_val;
    fura_cum += fura;
    if (fura < fura_min)
      fura_min = fura;
    if (fura > fura_max)
      fura_max=fura;
  }
  printf("%g %g %g\n",
	 fura_cum/(n_obs-start_fit),
	 fura_min,
	 fura_max);
  return 0;
}
